FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

# Install Anaconda
# Updating Ubuntu packages
RUN apt-get update && yes|apt-get upgrade

# Adding vim, git, wget and bzip2
RUN apt-get install -y vim git wget bzip2

# Anaconda installing
RUN wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -P /tmp/ 
RUN bash /tmp/Anaconda3-2020.02-Linux-x86_64.sh -b -p /opt/anaconda3
RUN rm -f /tmp/Anaconda3-2020.02-Linux-x86_64.sh
RUN ln -s /opt/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/anaconda3/ -follow -type f -name '*.a' -delete && \
    find /opt/anaconda3/ -follow -type f -name '*.js.map' -delete && \
    /opt/anaconda3/bin/conda clean -afy

# Set path to conda
ENV PATH /opt/anaconda3/bin:$PATH

# Updating Anaconda packages
#RUN conda update conda
#RUN conda update anaconda
#RUN conda update --all

# Install Pytorch
RUN conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

# Install the dependencies of training
RUN pip install tqdm tensorboardX
RUN pip install --index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
RUN git clone https://github.com/NVIDIA/apex /tmp/apex && \
    cd /tmp/apex && \
    pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./ && \
    rm -rf /tmp/apex
